### ISSUE TITLE
Review community splash screen

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/ACCESS-Hive#41]
Current splash screen needs updating with more meta information about the structure of the site and how to use and navigate it.

**Comment by kdruken** [comment]
Important things to have on front page:
- How to cite
- Acknowledgements
- Contact info
- Link to main site

**Comment by ccarouge** [comment]
@kdruken For the "How to cite" and "Acknowledgements", what does that refer to? I don't think of any reason to cite or acknowledge anything from ACCESS-Hub since it's a list of links to resources hosted elsewhere. Or is that simply a disclaimer? People should check the conditions of utilisation of each linked resource.

For ACCESS-NRI Hub, isn't it easier also to have the "How to cite" and "Acknowledgements" at the level of each linked resource/site?

**Comment by ccarouge** [comment]
Closed by #74

**Comment by kdruken** [comment]
@ccarouge - this was more referring to using the NRI content, perhaps on the community site it's all taken care of in the disclaimer to see the content's own terms of use etc. but for NRI generated or curated content, I think we do want to link or display our recommended citation and acknowledgement format. For the initial launch, this could be to direct to the main website page that has the acknowledgement statement maybe? For the citation part, I think we still have some work and registering of content, so this to me feels better suited to a later update once we have more content. How does that sound?

**Comment by ccarouge** [comment]
OK, thanks. I'll add the acknowledgement link to the home screen then.
